[mypy]
python_version = 3.12
explicit_package_bases = True
implicit_optional = True
check_untyped_defs = False
warn_return_any = False
warn_unused_ignores = False
exclude = venv/|scratch/|old_schedule_service\.py|scripts/|fixer.*\.py|patch_schedule.*\.py
